apiVersion: v1
kind: ConfigMap
metadata:
  name: form4-graphql-query
data:
  application.properties: |
    # Server Configuration
    quarkus.http.port=8080
    quarkus.http.host=0.0.0.0
    quarkus.http.root-path=/ora-form4

    # CORS Configuration
    quarkus.http.cors.origins=*
    quarkus.http.cors.methods=GET,POST,OPTIONS
    quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
    quarkus.http.cors.exposed-headers=location,info

    # Logging Configuration
    quarkus.log.level=DEBUG

    # SmallRye GraphQL UI
    quarkus.smallrye-graphql.ui.always-include=true

    # Caching details
    quarkus.cache.caffeine.metrics-enabled=true
    quarkus.cache.type=caffeine
    quarkus.cache.caffeine."ora-applications".initial-capacity=10
    quarkus.cache.caffeine."ora-applications".maximum-size=25
    quarkus.cache.caffeine."ora-applications".expire-after-write=900S
    quarkus.cache.caffeine."ora-reports-by-vacancy".initial-capacity=10
    quarkus.cache.caffeine."ora-reports-by-vacancy".maximum-size=50
    quarkus.cache.caffeine."ora-reports-by-vacancy".expire-after-write=1800S
    
    quarkus.mongodb.metrics.enabled=true
    # quarkus.mongodb.connection-string=mongodb://admin:UpscOra123@mongo.ora-upsc.svc.cluster.local:27017/ora_test?authSource=admin
    # quarkus.mongodb.database=ora_test

    quarkus.mongodb.oradb.connection-string=mongodb://10.212.108.66:2001
    quarkus.mongodb.oradb.database=UPSCAPPLICANTS
    quarkus.mongodb.oradb.credentials.username=upscora
    quarkus.mongodb.oradb.credentials.password=UpscORA123
    quarkus.mongodb.oradb.credentials.auth-source=admin
    application.id.prefix=126
    application.id.counter-id=EXAM_APPLICATION_ID
 
    mp.graphql.showErrorMessage=java.lang.RuntimeException
    quarkus.smallrye-graphql.error-extension-fields=exception,description,validationErrorType,classification
    quarkus.mongodb.cafdb.connection-string=mongodb://10.212.108.66:2001
    quarkus.mongodb.cafdb.database=UPSCAPPLICANTS
    quarkus.mongodb.cafdb.credentials.username=upscora
    quarkus.mongodb.cafdb.credentials.password=UpscORA123
    quarkus.mongodb.cafdb.credentials.auth-source=admin

    quarkus.mongodb.userdb.connection-string=mongodb://10.212.108.66:2001
    quarkus.mongodb.userdb.database=UPSCAPPLICANTS
    quarkus.mongodb.userdb.credentials.username=upscora
    quarkus.mongodb.userdb.credentials.password=UpscORA123
    quarkus.mongodb.userdb.credentials.auth-source=admin

    quarkus.mongodb.vacancy2026.connection-string=mongodb://10.212.108.66:2001
    quarkus.mongodb.vacancy2026.database=UPSCAPPLICANTS
    quarkus.mongodb.vacancy2026.credentials.username=upscora
    quarkus.mongodb.vacancy2026.credentials.password=UpscORA123
    quarkus.mongodb.vacancy2026.credentials.auth-source=admin

    
    # MongoDB Configuration
    #quarkus.mongodb.connection-string=mongodb://mongo.ora-upsc.svc.cluster.local:27017
    #quarkus.mongodb.database=ora_test
    #quarkus.mongodb.credentials.username=admin
    #quarkus.mongodb.credentials.password=UpscOra123
    #quarkus.mongodb.credentials.auth-source=admin

    quarkus.devservices.enabled=false

    # NGRP S3 document service
    #quarkus.rest-client.ngrp-api.url=https://ngrpstaging.nic.in
    quarkus.rest-client.ngrp-api.url=http://fileupload-svc.ora-upsc.svc.cluster.local:9002/ora
    #quarkus.rest-client.ngrp-api.disable-default-mapper=true
    ngrp.api.type=recruitment
    ngrp.api.lang=en
    ngrp.api.caf.type=ngrp-candidates

    quarkus.rest-client.caf-master.url=http://cafmaster-svc:8080/cafmaster
    quarkus.rest-client.ngrp-api.disable-default-mapper=true
