apiVersion: apps/v1
kind: Deployment
metadata:
  name: form4-graphql
  labels:
    app: form4-graphql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: form4-graphql
  template:
    metadata:
      labels:
        app: form4-graphql
    spec:
      containers:
        - name: form4-graphql
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /deployments/config/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configmapname }}            

