# ============================================================
# TASK 1: Git Repository se code clone karna
# Diagram step: "Clone Repository"
# ============================================================
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
      description: Git repository ka URL
    - name: revision
      type: string
      default: "feature/tekton-argocd-pipeline"
      description: Branch ya commit
  workspaces:
    - name: source
      description: Yahan code clone hoga, aage ke tasks isse use karenge
  steps:
    - name: clone
      image: 10.212.108.81:6001/ora/alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        echo ">>> Cloning $(params.repo-url) branch $(params.revision)"
        git clone --depth 1 --branch $(params.revision) $(params.repo-url) $(workspaces.source.path)/repo
        echo ">>> Clone done"
        ls -la $(workspaces.source.path)/repo
