replicaCount: 1
image:
  registry: registry.kube-system.svc.cluster.local
  repository: form4-graphql
  tag: "local-20260708-1208"
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
configmapname: "form4-graphql-query"
