replicaCount: 1

image:
  registry: registry.upsc.gov.in:5000
  repository: form4/form4-graphql
  tag: "2026-02-11-15-53"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
configmapname: "form4-graphql-query"


