apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: form4-graphql
    app.kubernetes.io/managed-by: Helm
data:
  application.properties: |
{{ .Values.applicationProperties | indent 4 }}
